# Generated by Django 5.1 on 2024-08-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='item_images/empty_image.jpg', upload_to='item_images'),
        ),
    ]
